language: elixir
sudo: false
script:
  - if [ "$CHECK_FORMATTED" = true ]; then mix format --check-formatted; fi
  - mix test
matrix:
  include:
    - elixir: 1.7.4
      otp_release: 19.3
    - elixir: 1.9.4
      otp_release: 22.1
      env: CHECK_FORMATTED=true
